// import LogoSvg from '@/Components/LogoSvg'
import { Logo } from "@/Components/Logo.jsx";
import PageLoader from "@/Components/PageLoader";
import ViewMoreBtn from "@/Components/ViewMoreBtn";
import s from '@/styles/Home.module.scss'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [pageLoading, setPageLoading] = useState(true);
  useEffect(() => {
    let timeoutId;
    setPageLoading(true)
    const onPageLoad = () => {
      console.log('page loaded');
      setTimeout(() => {
        setPageLoading(false)
      }, 2000);
    };

    if (document.readyState === 'complete') {
      onPageLoad();
    } else {
      window.addEventListener('load', onPageLoad, false);
      return () => {
        window.removeEventListener('load', onPageLoad);
        clearTimeout(timeoutId)
      };
    }
  }, []);
  return (
    <>
      <Head>
        <title>Test-1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${s.main} ${inter.className}`}>
        <PageLoader pageLoading={pageLoading} />
        <header data-hide="true">
          {/* <div className="header_header_gradation__rZ2Nw">

          </div> */}
          <div className={s.left}>
            <Link className={s.logo} href="/">
              <Logo />
            </Link>
          </div>
          <div className={s.right}>
            <Link className={s.right_top} href="/">TOP</Link>
          </div>
        </header>
        <div className={s.layout_container}>
          <div className={s.glCanvas_glCanvas}>

            <Image
              style={{ objectFit: 'contain' }}
              fill
              alt="human"
              src="https://nft.fluffyhugs.io/scene/webp/tex/human.webp"
            />
            <Image
              style={{ objectFit: 'contain', transform: 'translate(-141px, 354px)' }}
              fill
              alt="human"
              src="https://nft.fluffyhugs.io/scene/webp/tex/human.webp"
            />
            <Image
              style={{ objectFit: 'contain', transform: 'translate(141px,100px)' }}
              fill
              alt="human"
              src="https://nft.fluffyhugs.io/scene/webp/tex/human.webp"
            />
            <ViewMoreBtn />

            <div className={s.link}>
              {socialLinks.map(({ src, name, url }, index) => (
                <>
                  <div key={index} className={s.item}>
                    <Link href={url} target="_blank" rel="noopener noreferrer">

                      <Image width={40} height={40} src={src} alt={name} />
                    </Link>
                  </div>
                </>
              ))}
            </div>

          </div>
        </div>




        {/* <div >
          <section>
            1
          </section>
          <section >2</section>
          <section>3</section>
        </div> */}

      </main>
    </>
  )
}
const socialLinks = [
  {
    name: "discord",
    url: 'https://discord.com/invite/PmWf27cY6p',
    src: 'https://nft.fluffyhugs.io/logo/discord.svg'
  },
  {
    name: "opensea",
    url: 'https://opensea.io/ja/collection/fluffy-hugs89',
    src: 'https://nft.fluffyhugs.io/logo/opensea.svg'
  },
  {
    name: "twitter",
    url: 'https://twitter.com/FluffyHUGS_prj',
    src: 'https://nft.fluffyhugs.io/logo/twitter.svg'
  },
]

