// import LogoSvg from '@/Components/LogoSvg'
import { Logo } from "@/Components/Logo.jsx";
import s from '@/styles/Home.module.scss'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [pageLoading, setPageLoading] = useState(true);
  useEffect(() => {

    const onPageLoad = () => {
      console.log('page loaded');
      // do something else
    };

    // Check if the page has already loaded
    if (document.readyState === 'complete') {
      onPageLoad();
    } else {
      window.addEventListener('load', onPageLoad, false);
      // Remove the event listener when component unmounts
      return () => window.removeEventListener('load', onPageLoad);
    }
    let timeoutId;
    setPageLoading(true)
    timeoutId = setTimeout(() => {
      setPageLoading(false)
    }, 2000);
    return () => clearTimeout(timeoutId)
  }, []);


  return (
    <>
      <Head>
        <title>Test-1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${s.main} ${inter.className}`}>
        <div className={s.loading} data-loaded={!pageLoading}>
          <Image width={200} height={200} alt="loading" src={'https://nft.fluffyhugs.io/loading/loading.webp'} />
        </div>
        <header data-hide="true">
          {/* <div className="header_header_gradation__rZ2Nw">

          </div> */}
          <div className={s.left}>
            <Link className={s.logo} href="/">
              <Logo />
            </Link>
          </div>
          <div className="header_right__7cvlD">
            <Link className="header_right_top__UlXpu" href="/">TOP</Link>
          </div>
        </header>
        <div className={s.layout_container}>
          <div className={s.glCanvas_glCanvas}>
            <div className={s.viewMore_container} data-fade="index">
              <div className={s.viewMore}>
                <svg className={s.viewMore_svg} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 254.73 221.92" preserveAspectRatio="xMaxYMax " data-open_viewmore="false" data-fade="index">
                  <path fill="#203D99" className={s.viewMore_svg_shape} d="m225.68,15.74c-25.47-21.39-54.72-22.72-79.62,6.86-24.91,29.57-40.17,54.92-72.67,49.26-32.5-5.66-62.08,14.2-71.32,44.78-9.24,30.58,13.36,75.03,52.18,90.3,38.81,15.27,72.91,24.12,122.72.19,49.81-23.93,68.79-79.19,75.51-108.95,6.71-29.76-1.32-61.04-26.79-82.44Z"></path>
                <text className={s.viewMore_svg_text} x="81.9%" y="95.9%">view collection</text>
                </svg>
              </div>

            </div>
          </div>
        </div>




        {/* <div >
          <section>
            1
          </section>
          <section >2</section>
          <section>3</section>
        </div> */}

      </main>
    </>
  )
}
