// import LogoSvg from '@/Components/LogoSvg'
import { Logo } from "@/Components/Logo.jsx";
import ViewMoreBtn from "@/Components/ViewMoreBtn";
import s from '@/styles/Home.module.scss'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [pageLoading, setPageLoading] = useState(true);
  useEffect(() => {
    let timeoutId;
    setPageLoading(true)
    const onPageLoad = () => {
      console.log('page loaded');
      setTimeout(() => {
        setPageLoading(false)
      }, 1000);
    };

    if (document.readyState === 'complete') {
      onPageLoad();
    } else {
      window.addEventListener('load', onPageLoad, false);
      return () => {
        window.removeEventListener('load', onPageLoad);
        clearTimeout(timeoutId)
      };
    }
  }, []);
  return (
    <>
      <Head>
        <title>Test-1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${s.main} ${inter.className}`}>
        <div className={s.loading} data-loaded={!pageLoading}>
          <Image width={200} height={200} alt="loading" src={'https://nft.fluffyhugs.io/loading/loading.webp'} />
        </div>
        <header data-hide="true">
          {/* <div className="header_header_gradation__rZ2Nw">

          </div> */}
          <div className={s.left}>
            <Link className={s.logo} href="/">
              <Logo />
            </Link>
          </div>
          <div className="header_right__7cvlD">
            <Link className="header_right_top__UlXpu" href="/">TOP</Link>
          </div>
        </header>
        <div className={s.layout_container}>
          <div className={s.glCanvas_glCanvas}>
            <ViewMoreBtn/>
          </div>
        </div>




        {/* <div >
          <section>
            1
          </section>
          <section >2</section>
          <section>3</section>
        </div> */}

      </main>
    </>
  )
}

    
  